/** `07_text_strings.csv` 의 text_id — 오타 방지용 */

import type { GamePhase } from "./types";

export const TEXT_COPY_IDS = {
  modalSeasonEndTitle: "txt_modal_season_end_title",
  modalSeasonEndNoDice: "txt_modal_season_end_no_dice",
  modalMoneyHold: "txt_modal_money_hold",
  modalDiceRemaining: "txt_modal_dice_remaining",
  modalSeasonEndJailNoDice: "txt_modal_season_end_jail_no_dice",
  modalEndMoneyShort: "txt_modal_end_money_short",
  modalEndDiceShort: "txt_modal_end_dice_short",
  modalJailTitle: "txt_modal_jail_title",
  jailEscapeDouble: "txt_jail_escape_double",
  jailEscapeFail: "txt_jail_escape_fail",
  modalJailPendingGain: "txt_modal_jail_pending_gain",
  modalJailAfterDeduct: "txt_modal_jail_after_deduct",
  modalJailDiceLine: "txt_modal_jail_dice_line",
  modalDefaultResultTitle: "txt_modal_default_result_title",
  modalMoneyNoChange: "txt_modal_money_no_change",
  modalPendingGainLine: "txt_modal_pending_gain_line",
  modalPendingLossLine: "txt_modal_pending_loss_line",
  modalDiceRollOnly: "txt_modal_dice_roll_only",
  modalDiceBonusLine: "txt_modal_dice_bonus_line",
  modalSeasonEndFarewell: "txt_modal_season_end_farewell",
  modalDiceShortageTitle: "txt_modal_dice_shortage_title",
  modalDiceShortageBody: "txt_modal_dice_shortage_body",
  modalDiceShortageHint: "txt_modal_dice_shortage_hint",
  hudRollJail: "txt_hud_roll_jail",
  hudRollIdle: "txt_hud_roll_idle",
  hudRollTitleJail: "txt_hud_roll_title_jail",
  hudRollTitleIdle: "txt_hud_roll_title_idle",
  hudDiceStageIdle: "txt_hud_dice_stage_idle",
  btnModalConfirm: "txt_btn_modal_confirm",
  ariaDiceRegion: "txt_aria_dice_region",
  docTitle: "txt_doc_title",
  errBoundaryTitle: "txt_err_boundary_title",
  errBoundaryHint: "txt_err_boundary_hint",
  hudLblDice: "txt_hud_lbl_dice",
  hudLblStage: "txt_hud_lbl_stage",
  hudLblMoney: "txt_hud_lbl_money",
  hudStageJailSuffix: "txt_hud_stage_jail_suffix",
  hudStageLine: "txt_hud_stage_line",
  hudTimelineFoot: "txt_hud_timeline_foot",
  hudMultiplierHint: "txt_hud_multiplier_hint",
  hudAutoBtn: "txt_hud_auto_btn",
  hudAutoHint: "txt_hud_auto_hint",
  phaseIdle: "txt_phase_idle",
  phaseRolling: "txt_phase_rolling",
  phaseMoving: "txt_phase_moving",
  phaseResult: "txt_phase_result",
  phaseEnded: "txt_phase_ended",
  tileGoLanding: "txt_tile_go_landing",
  tileGoLandingSkip: "txt_tile_go_landing_skip",
  tileLandReward: "txt_tile_land_reward",
  tileStationShutdownOk: "txt_tile_station_shutdown_ok",
  tileStationShutdownBlock: "txt_tile_station_shutdown_block",
  tileLabelHeistS: "txt_tile_label_heist_s",
  tileLabelHeistM: "txt_tile_label_heist_m",
  tileLabelHeistL: "txt_tile_label_heist_l",
  tileStationHeist: "txt_tile_station_heist",
  tileChanceMoney: "txt_tile_chance_money",
  tileChanceWarp: "txt_tile_chance_warp",
  tileChanceDice: "txt_tile_chance_dice",
  tileCommunity: "txt_tile_community",
  tileCommunityDice: "txt_tile_community_dice",
  tileCommunityGo: "txt_tile_community_go",
  tileCommunityWarp: "txt_tile_community_warp",
  tileCornerVisit: "txt_tile_corner_visit",
  tileCornerPark: "txt_tile_corner_park",
  tileJailEnter: "txt_tile_jail_enter",
  tileTaxLow: "txt_tile_tax_low",
  tileTaxHigh: "txt_tile_tax_high",
  tileUnknown: "txt_tile_unknown",
} as const;

export const PHASE_TO_TEXT_ID: Record<GamePhase, string> = {
  idle: TEXT_COPY_IDS.phaseIdle,
  rolling: TEXT_COPY_IDS.phaseRolling,
  moving: TEXT_COPY_IDS.phaseMoving,
  result: TEXT_COPY_IDS.phaseResult,
  ended: TEXT_COPY_IDS.phaseEnded,
};
